excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://trylqyi.github.io
title: irregular posts about random stuff
tagline: verum ipsum factum
description: irregular journal
paginate: 5
